language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements-test.txt
# command to run tests
script:
  - python -m pytest --cov twitchrealtimehandler/ tests/ # pytest # or py.test for Python versions 3.5 and below
after_success:
  - bash <(curl -s https://codecov.io/bash)